baseURL = 'https://bmortgageservices.co.uk/'
languageCode = 'en-gb'
title = 'B Mortgage Services | Expert Mortgage & Insurance Advice'
theme = 'bms-theme'

[params]
  description = "Expert mortgage and insurance advice for individuals and employers. Whole-of-market access to 100+ lenders."
  author = "B Mortgage Services"
  phone = "01452 925209"
  email = "info@bmortgagesolutions.co.uk"
  address = "39 Teddington Gardens, Gloucester, GL4 6RL"
  tagline = "We Make Your Mortgage Simple"
  brandOrange = "#F05B28"
  brandCharcoal = "#2D2D2D"

[params.social]
  facebook = "https://facebook.com/bmortgageservices"
  linkedin = "https://linkedin.com/company/bmortgageservices"
  instagram = "https://instagram.com/bmortgageservices"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Individuals"
    url = "/individuals/"
    weight = 2
  [[menu.main]]
    name = "Employers"
    url = "/employers/"
    weight = 3
  [[menu.main]]
    name = "Financial Wellness"
    url = "/wellness/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
