baseURL = 'https://bmortgageservices.co.uk/'
languageCode = 'en-gb'
title = 'B Mortgage Services | Expert Mortgage & Insurance Advice'
theme = 'bms-theme'

[params]
  description = "Expert mortgage and insurance advice for individuals and employers. Access to a wide range of lenders."
  author = "B Mortgage Services"
  phone = "01452 925209"
  email = "info@bmortgagesolutions.co.uk"
  address = "39 Teddington Gardens, Gloucester, GL4 6RL"
  tagline = "We Make Your Mortgage Simple"
  brandOrange = "#F05B28"
  brandCharcoal = "#2D2D2D"

[params.social]
  facebook = "https://facebook.com/bmortgageservices"
  linkedin = "https://linkedin.com/company/bmortgageservices"
  instagram = "https://instagram.com/bmortgageservices"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Individuals"
    url = "/individuals/"
    weight = 2
    identifier = "individuals"
  [[menu.main]]
    name = "Protection"
    url = "/individuals/protection/"
    weight = 1
    parent = "individuals"
  [[menu.main]]
    name = "Employers"
    url = "/employers/"
    weight = 3
  [[menu.main]]
    name = "Tools"
    url = "#"
    weight = 4
    identifier = "tools"
  [[menu.main]]
    name = "Affordability Calculator"
    url = "/affordability-calculator/"
    weight = 1
    parent = "tools"
  [[menu.main]]
    name = "Budget Planner"
    url = "/budget-planner/"
    weight = 2
    parent = "tools"
  [[menu.main]]
    name = "Financial Wellness"
    url = "/wellness/"
    weight = 3
    parent = "tools"
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
